apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: team-app1
  name: team-app1
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: team-app1
  name: team-app2
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: frontend-web
  name: app1
  namespace: team-app1
spec:
  containers:
  - args:
    - sleep
    - 60m
    image: busybox:stable
    name: app
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hr-web
  name: app2
  namespace: team-app1
spec:
  containers:
  - args:
    - sleep
    - 60m
    image: busybox:stable
    name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: team-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: lehuyhuan/simple-api:python
        name: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: team-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:6.0.20-alpine3.18
        name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: team-app2
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: api
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: team-app2
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
